author: eccentric_nz
description: Allow players to have separate inventories for each game mode (Creative and Survival).
main: me.eccentric_nz.gamemodeinventories.GameModeInventories
name: GameModeInventories-OG
load: POSTWORLD
softdepend: [ Multiverse-Core,MultiWorld,CoreProtect ]
version: ${version}
api-version: ${apiVersion}
libraries:
  - com.zaxxer:HikariCP:5.0.1
permissions:
  gamemodeinventories.use:
    default: true
    description: Allow players to have separate inventories for each gamemode.
  gamemodeinventories.death:
    default: op
    description: Allow players to save their inventories on death, and restore them on respawn.
  gamemodeinventories.bypass:
    default: op
    description: Allow players to access inventories in CREATIVE mode even if 'restrict_creative' is true. Also allow CREATIVE players to drop and pickup items.
  gamemodeinventories.spectator:
    default: op
    description: Allow players to switch to Gamemode SPECTATOR.
  gamemodeinventories.admin:
    default: op
    description: Allow players to change config options.
  gamemodeinventories.toggle:
    default: op
    description: Allow players to toggle between CREATIVE and SURVIVAL with /gmic.
commands:
  gmi:
    aliases: [ gmic ]
    description: Allow players to change config options or toggle CREATIVE mode.
    usage: /<command> [config option]